### ISSUE TITLE
How to run the code. Where can I find the Dataset 

### ISSUE THREAD

**Issue by PalgunaGopireddy** [cidcom/human-walking-radar-simulator#1]
The commands to run the code are not given. 
All the programs are in Python. I am confused about how to run.

Also, I do not see the dataset anywhere.

**Comment by mikonvergence** [comment]
The `dataset_generator_tool.py` (https://github.com/cidcom/human-walking-radar-simulator/blob/main/dataset_generator_tool.py) demonstrates how to use the `generate()` function to produce the samples and how they're stored.

**Comment by PalgunaGopireddy** [comment]
I am confused about how this repository generates the dataset without any raw dataset. 

I observed all the files are giving `ImportError: attempted relative import with no known parent package` due to the incorrect import strategy. All the files in this repository used `from .`, which is unnecessary as all the files are in the same library.  So I removed `.` from the imports. Just used `from file import *`

Anyway, I ran `python dataset_generator_tool.py`. 
But It has given error
```
Traceback (most recent call last):
  File "G:\Palguna\github\human-walking-radar-simulator-main\dataset_generator_tool.py", line 141, in <module>
    generate(config, n_samples)
  File "G:\Palguna\github\human-walking-radar-simulator-main\dataset_generator_tool.py", line 102, in generate
    conf_file.write(config.pretty())
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\omegaconf\dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\omegaconf\_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\omegaconf\dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\omegaconf\dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\omegaconf\basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\omegaconf\dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key pretty
    full_key: pretty
    object_type=dict
```
So I am a little bit confused here. I guess it is coming because of `omegaconf` library.

Could you run the code as it is after downloading it from this git repository and tell me if have you encountered any problems? or it is running well.Tell me where I am wrong.

**Comment by mikonvergence** [comment]
Hi,

I've now fixed the issues and restructured the directory a bit. I've tested generation of 10 samples and it seems to work (https://github.com/cidcom/human-walking-radar-simulator/blob/main/01-Demo-Notebook.ipynb).

This tool generates simulated Doppler returns based on an existing model of human motion - so it does not need any raw dataset. The related paper contains more details on how it can be used https://ieeexplore.ieee.org/document/9454986.

The code is somewhat outdated and could be improved in various ways - unfortunately, I don't currently have capacity to maintain it. If anyone wants to create pull requests with further fixes / improvements, that's definitely an option.

**Comment by PalgunaGopireddy** [comment]
Thanks @mikonvergence . Though the line 70 in `dataset_generator_tool.py` is giving error as of [pandas 2.0, 'append' is deprecated for dataframe object](https://stackoverflow.com/a/75956237/21763726) . I will resolve it and understand the code, and get back to you if anything is needed. Thank you
